In [1]:
import pymysql

import pandas as pd

db = pymysql.connect(host='localhost',port=int(3306),user='root',passwd='12345678', 
                    cursorclass=pymysql.cursors.DictCursor)

# try: 
#     cursorInstance.execute("CREATE DATABASE data_warehouse")
#     print('Database was successfully created')
# except: 
#     print('Database existed')
    
db = pymysql.connect(host='localhost',port=int(3306),user='root',passwd='12345678', 
                    db='financialservice', cursorclass=pymysql.cursors.DictCursor)

cursorInstance = db.cursor()
cursorInstance.execute("SHOW DATABASES")
databaseList = cursorInstance.fetchall()

In [2]:
def run(command, *args):
    cursorInstance.execute(command, args)

def get():
    return cursorInstance.fetchall()
# df = pd.read_sql(databaseList, con=db)

def format_id(a, length):
    (length - len(a)) * '0' + str(a)

In [3]:
borrower_csv = pd.read_csv('./borrower_table.csv')
loan_csv = pd.read_csv('./loan_table.csv')

import collections
borrower_id_counter = collections.Counter(list(borrower_csv['loan_id']))
loan_id_counter = collections.Counter(list(loan_csv['loan_id']))

print(borrower_id_counter == loan_id_counter)

True

In [4]:
import datetime
import random

def random_date(year):
    start_date = datetime.date(year, 1, 1)
    end_date = datetime.date(year, 12, 31)

    time_between_dates = end_date - start_date
    days_between_dates = time_between_dates.days
    random_number_of_days = random.randrange(days_between_dates)
    
    return start_date + datetime.timedelta(days=random_number_of_days)

In [5]:
import numpy as np

joined_csv = pd.merge(borrower_csv, loan_csv, how='inner', on=['loan_id'])
joined_csv['customer_id'] = np.arange(len(joined_csv)) + 1
joined_csv['date'] = pd.to_datetime(joined_csv['date'], format="%Y-%m-%d")

Random start date

In [6]:
from tqdm import tqdm


for index, row in tqdm(joined_csv.iterrows()):
        joined_csv['date'][index] = random_date(2012 + np.random.choice([0, 1, 2, 3, 4, 5, 6, 7, 8],  p=[0.09, 0.1, 0.1, 0.11, 0.11, 0.12, 0.12, 0.13, 1 - 0.09 - 0.1 - 0.1 - 0.11 - 0.11 - 0.12 - 0.12 - 0.13]))

0it [00:00, ?it/s]ipykernel_launcher:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
101100it [01:56, 870.41it/s]

In [7]:
joined_csv['date'] = pd.to_datetime(joined_csv['date'], format="%Y-%m-%d")

In [8]:
joined_csv['year'] = joined_csv['date'].dt.year

joined_csv['month'] = joined_csv['date'].dt.month

joined_csv['day'] = joined_csv['date'].dt.day

joined_csv['quarter'] = joined_csv['date'].dt.quarter

joined_csv['date_of_birth'] = joined_csv['year'] - joined_csv['age']

joined_csv['date_of_birth'] = joined_csv['date_of_birth'].apply(random_date)

joined_csv['date_of_birth'] = pd.to_datetime(joined_csv['date_of_birth'], format="%Y-%m-%d")

Random Branch

In [9]:
from faker import Faker

fake = Faker('en_US')

BRANCH_COUNT = 20


branch_addresses = ["Đường Kim Ngọc, Thành phố Vĩnh Yên, Tỉnh Vĩnh Phúc", 
                    "Hai Bà Trưng, Quận Hoàn Kiếm, Thành phố Hà Nội",
                    "Thợ Nhuộm, Quận Hoàn Kiếm, Thành phố Hà Nội", 
                    "Lê Thánh Tông, Quận Hoàn Kiếm, Thành phố Hà Nội",
                    "Trần Quang Khải, Quận Hoàn Kiếm, Thành phố Hà Nội",
                    "Hàng Tre, Quận Hoàn Kiếm, Thành phố Hà Nội",
                    "Huỳnh Thúc Kháng, Quận Đống Đa, Thành phố Hà Nội",
                    "Trần Duy Hưng, Quận Cầu Giấy, Thành phố Hà Nội",
                    "Phạm Hùng, Nam Từ Liêm, Thành phố Hà Nội", 
                    "Phan Đình Phùng, Quận Ba Đình, Thành phố Hà Nội", 
                    "Võ Văn Kiệt, Quận 1, Thành phố Hồ Chí Minh", 
                    "Hàm Nghi, Quận 1, Thành phố Hồ Chí Minh", 
                    "Lê Thánh Tôn, Quận 1, Thành phố Hồ Chí Minh", 
                    "Bùi Thị Xuân, Quận 1, Thành phố Hồ Chí Minh", 
                    "Phó Đức Chính, Quận 1, Thành phố Hồ Chí Minh", 
                    "Nguyễn Công Trứ, Quận 1, Thành phố Hồ Chí Minh",
                    "Võ Văn Tần, Quận 3, Thành phố Hồ Chí Minh", 
                    "Nam Kỳ Khởi Nghĩa, Quận 3, Thành phố Hồ Chí Minh", 
                    "Nguyễn Thị Diệu, Quận 3, Thành phố Hồ Chí Minh",
                    "Đường Hoà Bình, Quận Ninh Kiều, Thành phố Cần Thơ", 
                    "Phan Đình Phùng, Quận Ninh Kiều, Thành phố Cần Thơ",
                    "Võ Văn Tần, Quận Ninh Kiều, Thành phố Cần Thơ", 
                    "Đường Hùng Vương,Thành phố Móng Cái, Tỉnh Quảng Ninh", 
                    "Trần Hưng Đạo, Thành phố Hạ Long, Tỉnh Quảng Ninh",
                    "Đường Hùng Vương, Thành phố Móng Cái, Tỉnh Quảng Ninh", 
                    "Đại lộ Bình Dương, Thành phố Thủ Dầu Một, Tỉnh Bình Dương",
                    "Đường ĐT743, Thị xã Dĩ An, Tỉnh Bình Dương",
                    "Trường Chinh, Thị xã Bà Rịa, Tỉnh Bà Rịa - Vũng Tàu", 
                    "Quốc lộ 51, Huyện Tân Thành, Tỉnh Bà Rịa - Vũng Tàu",
                    "Thống Nhất, Thành phố Vũng Tàu, Tỉnh Bà Rịa - Vũng Tàu",
                    "Trần Hưng Đạo, Thành phố Vũng Tàu, Tỉnh Bà Rịa - Vũng Tàu",
                    "Đường Nguyễn Trung Trực, Phú Quốc, Kiên Giang",
                    "Đường Trần Phú, Rạch Giá, Kiên Giang",
                    "Hùng Vương, Thành phố Quảng Ngãi, Tỉnh Quảng Ngãi",
                    "Trung An, Huyện Bình Sơn, Tỉnh Quảng Ngãi",
                    "Đường Lê Lợi, Thành phố Plei Ku, Tỉnh Gia Lai",
                    "Nguyễn Tất Thành, Thành phố Plei Ku, Tỉnh Gia Lai",
                    "Trần Phú, Thành phố Plei Ku, Tỉnh Gia Lai",
                    "Lê Lợi, Vĩnh Long, Vĩnh Long",
                    "KCN Phú Tài, Thành phố Quy Nhơn, Tỉnh Bình Định",
                    "Lê Duẩn, Thành phố Quy Nhơn, Tỉnh Bình Định", 
                    "Lê Hồng Phong, Thành phố Quy Nhơn, Tỉnh Bình Định", 
                    "Lê Thị Pha, Thành phố Bảo Lộc, Tỉnh Lâm Đồng",
                    "Đường 30/4, Thành phố Tây Ninh, Tỉnh Tây Ninh",
                    "Đường Trần Phú, Thành phố Kon Tum, Tỉnh Kon Tum",
                    "Nguyễn Công Trứ, Thành phố Vị Thanh, Hậu Giang", 
                    "Đại Lộ Đồng Khởi, Thành phố Bến Tre, Bến Tre", 
                    "Qưới Sơn, Châu Thành, Bến Tre", 
                    "Duy Tân, Thành phố Tuy Hoà, Tỉnh Phú Yên", 
                    "Đường Lê Thánh Tôn, Thành phố Trà Vinh, Tỉnh Trà Vinh"]

print(len(branch_addresses))
num_branch = len(branch_addresses)
for i in range(num_branch):
    print("i = ", i)
    building_number = fake.building_number()
    address = branch_addresses[i]
    sql = f'INSERT INTO branch VALUES ({i}, "{building_number}, {branch_addresses[i]}")'
    run(sql)
    
db.commit()

50
i =  0
i =  1
i =  2
i =  3
i =  4
i =  5
i =  6
i =  7
i =  8
i =  9
i =  10
i =  11
i =  12
i =  13
i =  14
i =  15
i =  16
i =  17
i =  18
i =  19
i =  20
i =  21
i =  22
i =  23
i =  24
i =  25
i =  26
i =  27
i =  28
i =  29
i =  30
i =  31
i =  32
i =  33
i =  34
i =  35
i =  36
i =  37
i =  38
i =  39
i =  40
i =  41
i =  42
i =  43
i =  44
i =  45
i =  46
i =  47
i =  48
i =  49

Random customers

Random loan category

In [10]:
# db.rollback()

category_id = 0
id2time = {}
id2rate = {}
for lifespan in [6, 12, 18, 24, 30, 36]:
    for purpose in ['business', 'investment', 'other', 'emergency_funds', 'home']:
        for is_secured in [0, 1]: 
            if is_secured == 0: 
                rate = round(random.uniform(16, 25), 2)
            else: 
                rate = round(random.uniform(10, 12), 2)
            
            new_lifespan = lifespan * 30
            
            sql = 'INSERT INTO loan_category VALUES (%s, %s, %s, %s, %s)'
            run(sql, category_id, new_lifespan, rate, purpose, is_secured)
            id2time[category_id] = new_lifespan
            id2rate[category_id] = rate 
            
            category_id += 1
            
            
db.commit()

In [11]:
print(joined_csv['date'])
print(type(joined_csv['date'][0]))

0        2018-09-08
1        2016-09-06
2        2013-02-08
3        2020-11-23
4        2013-08-18
            ...
101095   2016-05-23
101096   2020-01-21
101097   2020-10-28
101098   2019-12-08
101099   2017-06-04
Name: date, Length: 101100, dtype: datetime64[ns]
<class 'pandas._libs.tslibs.timestamps.Timestamp'>

In [12]:
import math 
from uuid import uuid4
import time
db.rollback()

import datetime
from datetime import timedelta
import calendar
from tqdm import tqdm

def add_months(sourcedate, months):
    month = sourcedate.month - 1 + months
    year = sourcedate.year + month // 12
    month = month % 12 + 1
    day = min(sourcedate.day, calendar.monthrange(year,month)[1])
    return datetime.date(year, month, day)

def random_datetime(date):
    date_time = datetime.datetime(date.year, date.month, date.day)
    end = date_time + timedelta(days=1)
    return date_time + (end - date_time) * random.random()


family_names = ["Nguyễn", "Trần", "Phạm", "Đặng", "Hoàng", "Hồ", "Vũ", "Cao", "Trịnh"]
names = ["Sơn", "Mạnh", "Huy", "Nam", "Trang", "Hải", "Yến", "Thúy", "Châu", "Phi", "Huy", "Tú"]
print(len(joined_csv))

loan_id = 0
account_id = 0
num_iterated = 0
started_time = datetime.datetime.now()
NUM_CUSTOMER = 20000
for index, row in joined_csv.iterrows():
    num_iterated += 1
    if (num_iterated >= NUM_CUSTOMER):
        break
    if (num_iterated % 100 == 0):
        current_time = datetime.datetime.now()
        print("Number generated = ", num_iterated, " time ellapsed = ", current_time - started_time)
    customer_id = row['customer_id']
    customer_name = np.random.choice(family_names) + " " + np.random.choice(names)
    yearly_salary = row['yearly_salary']
    date_of_birth = row['date_of_birth']
    address = fake.building_number() + ", " + random.choice(branch_addresses)
    is_employed = row['is_employed']
    marital_status = np.random.choice([0, 1, 2, 3], p=[0.69, 0.22, 0.01, 0.08])
    if (yearly_salary == 0):
        continue
    
    sql = 'INSERT INTO customer VALUES (%s, %s, %s, %s, %s, %s, %s)'
    run(sql, customer_id, customer_name, is_employed, date_of_birth, address, 
        marital_status, yearly_salary)

    n_accounts = 1
    data_src = ['saving_amount', 'checking_amount',]
    for i in range(n_accounts):
        #generate random account for a customer
        branch_id = random.randint(0, num_branch - 1)
        create_date = random_date(random.randint(2010, 2012))
        balance = row[data_src[i]]
        sql = 'INSERT INTO account VALUES (%s, %s, %s, %s, %s)'
        account_id += 1
        run(sql, account_id, create_date, balance, customer_id, branch_id)
        
        if (random.randint(0, 100) < 30):
            #random a loan for each customer.
            loan_id += 1
            lifespan_id = np.random.choice([0, 1, 2, 3, 4, 5], p=[0.21, 0.25, 0.24, 0.15, 0.10, 0.05])
            purpose_id = np.random.choice([0, 1, 2, 3, 4], p=[0.23, 0.22, 0.14, 0.165, 0.245])
            is_secured = np.random.choice([0, 1], p=[0.4, 0.6])
            category_id = (lifespan_id * 5 + purpose_id) * 2 + is_secured
            #print(category_id)
            start_date = joined_csv['date'][customer_id]
            monthly_salary = yearly_salary // 12 
            life_cost =  monthly_salary * random.randint(20, 50) / 100
            redundant_money = monthly_salary - life_cost
            monthly_rate = id2rate[category_id] / 12
            available_amount = (redundant_money * (1 + monthly_rate))
            lifespan = id2time[category_id]
            lifespan_by_month = lifespan // 30
            lifespan_redundant_money = redundant_money * lifespan_by_month
            lifespan_rate = monthly_rate * lifespan_by_month
            max_available_amount = lifespan_redundant_money / (1 + lifespan_rate) 
            available_amount = max_available_amount * random.randint(40, 50) / 100
        
            sql = 'INSERT INTO loan VALUES (%s, %s, %s, %s, %s)'
            run(sql, loan_id, available_amount, start_date, account_id, category_id)
            
            paid_times = lifespan_by_month
            bad_debt_rate = 0.10
            start_year = start_date.to_pydatetime().year
            available_amount *= (1 - 0.05 * (2020 - start_year))    
            if (start_year <= 2017 and start_year >= 2015):
                bad_debt_rate = 0.05
            elif (start_year == 2018):
                bad_debt_rate = 0.03
            elif (start_year >= 2019):
                bad_debt_rate = 0.01
            
            is_bad_debt = np.random.choice([0, 1], p=[bad_debt_rate, 1 - bad_debt_rate])
            if (is_employed == 0):
                bad_debt_rate *= 1.3
            
            if (marital_status == 0):
                bad_debt_rate *= 1.1

            if (yearly_salary > 25000):
                bad_debt_rate *= 0.65
            elif (yearly_salary > 20000):
                bad_debt_rate *= 0.7
            elif (yearly_salary > 15000):
                bad_debt_rate *= 0.8

            if (is_bad_debt):
                paid_times = paid_times - np.random.choice([1, 2, 3], p=[0.4, 0.36, 0.24])
            monthly_amount = int(available_amount * monthly_rate / 100) + available_amount // lifespan_by_month    
            #print("monthly_rate =", monthly_rate)
            #print("available = ", available_amount)
            #print("monthly = ", monthly_amount)
            if (paid_times < 0):
                continue
            for i in range(paid_times + 1):
                #generate loan transactions for a loan
                pay_date = add_months(start_date, i)
                now = datetime.datetime.now() 
                now = add_months(now, 0)
                if pay_date > now: 
                    break
                
                transaction_id = uuid4()
                if i == 0: 
                    transaction_amount = -available_amount
                else:
                    transaction_amount = monthly_amount 

                sql = 'INSERT INTO loan_transaction VALUES (%s, %s, %s, %s)'
                run(sql, transaction_id, pay_date, transaction_amount, loan_id)

print("Generated")         
db.commit()

101100
Number generated =  100  time ellapsed =  0:00:00.822685
Number generated =  200  time ellapsed =  0:00:01.002439
Number generated =  300  time ellapsed =  0:00:01.147652
Number generated =  400  time ellapsed =  0:00:01.288936
Number generated =  500  time ellapsed =  0:00:01.441939
Number generated =  600  time ellapsed =  0:00:01.604742
Number generated =  700  time ellapsed =  0:00:01.779114
Number generated =  800  time ellapsed =  0:00:01.938650
Number generated =  900  time ellapsed =  0:00:02.128575
Number generated =  1000  time ellapsed =  0:00:02.303653
Number generated =  1100  time ellapsed =  0:00:02.466937
Number generated =  1200  time ellapsed =  0:00:02.613167
Number generated =  1300  time ellapsed =  0:00:02.760856
Number generated =  1400  time ellapsed =  0:00:02.916325
Number generated =  1500  time ellapsed =  0:00:03.128733
Number generated =  1600  time ellapsed =  0:00:03.351441
Number generated =  1700  time ellapsed =  0:00:03.512379
Number generated =  1800  time ellapsed =  0:00:03.667826
Number generated =  1900  time ellapsed =  0:00:03.841856
Number generated =  2000  time ellapsed =  0:00:04.016650
Number generated =  2100  time ellapsed =  0:00:04.192967
Number generated =  2200  time ellapsed =  0:00:04.345991
Number generated =  2300  time ellapsed =  0:00:04.469978
Number generated =  2400  time ellapsed =  0:00:04.638246
Number generated =  2500  time ellapsed =  0:00:04.753247
Number generated =  2600  time ellapsed =  0:00:04.900852
Number generated =  2700  time ellapsed =  0:00:05.041824
Number generated =  2800  time ellapsed =  0:00:05.194245
Number generated =  2900  time ellapsed =  0:00:05.434802
Number generated =  3000  time ellapsed =  0:00:05.563456
Number generated =  3100  time ellapsed =  0:00:05.692237
Number generated =  3200  time ellapsed =  0:00:05.872754
Number generated =  3300  time ellapsed =  0:00:06.041304
Number generated =  3400  time ellapsed =  0:00:06.211928
Number generated =  3500  time ellapsed =  0:00:06.382922
Number generated =  3600  time ellapsed =  0:00:06.551512
Number generated =  3700  time ellapsed =  0:00:06.742759
Number generated =  3800  time ellapsed =  0:00:06.899588
Number generated =  3900  time ellapsed =  0:00:07.023626
Number generated =  4000  time ellapsed =  0:00:07.194199
Number generated =  4100  time ellapsed =  0:00:07.381903
Number generated =  4200  time ellapsed =  0:00:07.559736
Number generated =  4300  time ellapsed =  0:00:07.734275
Number generated =  4400  time ellapsed =  0:00:07.881812
Number generated =  4500  time ellapsed =  0:00:08.047424
Number generated =  4600  time ellapsed =  0:00:08.217208
Number generated =  4700  time ellapsed =  0:00:08.400015
Number generated =  4800  time ellapsed =  0:00:08.597813
Number generated =  4900  time ellapsed =  0:00:08.744407
Number generated =  5000  time ellapsed =  0:00:08.883036
Number generated =  5100  time ellapsed =  0:00:09.073675
Number generated =  5200  time ellapsed =  0:00:09.216837
Number generated =  5300  time ellapsed =  0:00:09.380433
Number generated =  5400  time ellapsed =  0:00:09.532805
Number generated =  5500  time ellapsed =  0:00:09.718308
Number generated =  5600  time ellapsed =  0:00:09.858086
Number generated =  5700  time ellapsed =  0:00:10.060574
Number generated =  5800  time ellapsed =  0:00:10.211379
Number generated =  5900  time ellapsed =  0:00:10.350416
Number generated =  6000  time ellapsed =  0:00:10.505405
Number generated =  6100  time ellapsed =  0:00:10.624087
Number generated =  6200  time ellapsed =  0:00:10.846846
Number generated =  6300  time ellapsed =  0:00:11.038522
Number generated =  6400  time ellapsed =  0:00:11.273993
Number generated =  6500  time ellapsed =  0:00:11.455746
Number generated =  6600  time ellapsed =  0:00:11.617851
Number generated =  6700  time ellapsed =  0:00:11.769474
Number generated =  6800  time ellapsed =  0:00:11.902364
Number generated =  6900  time ellapsed =  0:00:12.084874
Number generated =  7000  time ellapsed =  0:00:12.260404
Number generated =  7100  time ellapsed =  0:00:12.478920
Number generated =  7200  time ellapsed =  0:00:12.653839
Number generated =  7300  time ellapsed =  0:00:12.860307
Number generated =  7400  time ellapsed =  0:00:13.015895
Number generated =  7500  time ellapsed =  0:00:13.226293
Number generated =  7600  time ellapsed =  0:00:13.411376
Number generated =  7700  time ellapsed =  0:00:13.551188
Number generated =  7800  time ellapsed =  0:00:13.741629
Number generated =  7900  time ellapsed =  0:00:13.882253
Number generated =  8000  time ellapsed =  0:00:14.042830
Number generated =  8100  time ellapsed =  0:00:14.226023
Number generated =  8200  time ellapsed =  0:00:14.442448
Number generated =  8300  time ellapsed =  0:00:14.580501
Number generated =  8400  time ellapsed =  0:00:14.717782
Number generated =  8500  time ellapsed =  0:00:14.882674
Number generated =  8600  time ellapsed =  0:00:15.041250
Number generated =  8700  time ellapsed =  0:00:15.177883
Number generated =  8800  time ellapsed =  0:00:15.366635
Number generated =  8900  time ellapsed =  0:00:15.528044
Number generated =  9000  time ellapsed =  0:00:15.684881
Number generated =  9100  time ellapsed =  0:00:16.014855
Number generated =  9200  time ellapsed =  0:00:16.158570
Number generated =  9300  time ellapsed =  0:00:16.328153
Number generated =  9400  time ellapsed =  0:00:16.492183
Number generated =  9500  time ellapsed =  0:00:16.655714
Number generated =  9600  time ellapsed =  0:00:16.799330
Number generated =  9700  time ellapsed =  0:00:16.933499
Number generated =  9800  time ellapsed =  0:00:17.067141
Number generated =  9900  time ellapsed =  0:00:17.275612
Number generated =  10000  time ellapsed =  0:00:17.409853
Number generated =  10100  time ellapsed =  0:00:17.600368
Number generated =  10200  time ellapsed =  0:00:17.747307
Number generated =  10300  time ellapsed =  0:00:17.896567
Number generated =  10400  time ellapsed =  0:00:18.059103
Number generated =  10500  time ellapsed =  0:00:18.247835
Number generated =  10600  time ellapsed =  0:00:18.382541
Number generated =  10700  time ellapsed =  0:00:18.536811
Number generated =  10800  time ellapsed =  0:00:18.650830
Number generated =  10900  time ellapsed =  0:00:18.802497
Number generated =  11000  time ellapsed =  0:00:18.930834
Number generated =  11100  time ellapsed =  0:00:19.116957
Number generated =  11200  time ellapsed =  0:00:19.293548
Number generated =  11300  time ellapsed =  0:00:19.454658
Number generated =  11400  time ellapsed =  0:00:19.590558
Number generated =  11500  time ellapsed =  0:00:19.750813
Number generated =  11600  time ellapsed =  0:00:19.970778
Number generated =  11700  time ellapsed =  0:00:20.134487
Number generated =  11800  time ellapsed =  0:00:20.335203
Number generated =  11900  time ellapsed =  0:00:20.585119
Number generated =  12000  time ellapsed =  0:00:20.705986
Number generated =  12100  time ellapsed =  0:00:20.851322
Number generated =  12200  time ellapsed =  0:00:21.017257
Number generated =  12300  time ellapsed =  0:00:21.184876
Number generated =  12400  time ellapsed =  0:00:21.319039
Number generated =  12500  time ellapsed =  0:00:21.500447
Number generated =  12600  time ellapsed =  0:00:21.650064
Number generated =  12700  time ellapsed =  0:00:21.830582
Number generated =  12800  time ellapsed =  0:00:21.982176
Number generated =  12900  time ellapsed =  0:00:22.148637
Number generated =  13000  time ellapsed =  0:00:22.317151
Number generated =  13100  time ellapsed =  0:00:22.539742
Number generated =  13200  time ellapsed =  0:00:22.761546
Number generated =  13300  time ellapsed =  0:00:22.941481
Number generated =  13400  time ellapsed =  0:00:23.114020
Number generated =  13500  time ellapsed =  0:00:23.273954
Number generated =  13600  time ellapsed =  0:00:23.483360
Number generated =  13700  time ellapsed =  0:00:23.675132
Number generated =  13800  time ellapsed =  0:00:23.878347
Number generated =  13900  time ellapsed =  0:00:24.207102
Number generated =  14000  time ellapsed =  0:00:24.372710
Number generated =  14100  time ellapsed =  0:00:24.550805
Number generated =  14200  time ellapsed =  0:00:24.720216
Number generated =  14300  time ellapsed =  0:00:24.912615
Number generated =  14400  time ellapsed =  0:00:25.076548
Number generated =  14500  time ellapsed =  0:00:25.230138
Number generated =  14600  time ellapsed =  0:00:25.390708
Number generated =  14700  time ellapsed =  0:00:25.621580
Number generated =  14800  time ellapsed =  0:00:25.783431
Number generated =  14900  time ellapsed =  0:00:25.974579
Number generated =  15000  time ellapsed =  0:00:26.118109
Number generated =  15100  time ellapsed =  0:00:26.309905
Number generated =  15200  time ellapsed =  0:00:26.542853
Number generated =  15300  time ellapsed =  0:00:26.751780
Number generated =  15400  time ellapsed =  0:00:26.894065
Number generated =  15500  time ellapsed =  0:00:27.066526
Number generated =  15600  time ellapsed =  0:00:27.240878
Number generated =  15700  time ellapsed =  0:00:27.381587
Number generated =  15800  time ellapsed =  0:00:27.634825
Number generated =  15900  time ellapsed =  0:00:27.765662
Number generated =  16000  time ellapsed =  0:00:27.932329
Number generated =  16100  time ellapsed =  0:00:28.075432
Number generated =  16200  time ellapsed =  0:00:28.226135
Number generated =  16300  time ellapsed =  0:00:28.349302
Number generated =  16400  time ellapsed =  0:00:28.510819
Number generated =  16500  time ellapsed =  0:00:28.677939
Number generated =  16600  time ellapsed =  0:00:28.951292
Number generated =  16700  time ellapsed =  0:00:29.156183
Number generated =  16800  time ellapsed =  0:00:29.317458
Number generated =  16900  time ellapsed =  0:00:29.560297
Number generated =  17000  time ellapsed =  0:00:29.762466
Number generated =  17100  time ellapsed =  0:00:30.001458
Number generated =  17200  time ellapsed =  0:00:30.314540
Number generated =  17300  time ellapsed =  0:00:30.487851
Number generated =  17400  time ellapsed =  0:00:30.710161
Number generated =  17500  time ellapsed =  0:00:30.883165
Number generated =  17600  time ellapsed =  0:00:31.089104
Number generated =  17700  time ellapsed =  0:00:31.261703
Number generated =  17800  time ellapsed =  0:00:31.495913
Number generated =  17900  time ellapsed =  0:00:31.747802
Number generated =  18000  time ellapsed =  0:00:31.959368
Number generated =  18100  time ellapsed =  0:00:32.151609
Number generated =  18200  time ellapsed =  0:00:32.319415
Number generated =  18300  time ellapsed =  0:00:32.600898
Number generated =  18400  time ellapsed =  0:00:32.778498
Number generated =  18500  time ellapsed =  0:00:32.936461
Number generated =  18600  time ellapsed =  0:00:33.104533
Number generated =  18700  time ellapsed =  0:00:33.268082
Number generated =  18800  time ellapsed =  0:00:33.517835
Number generated =  18900  time ellapsed =  0:00:33.748994
Number generated =  19000  time ellapsed =  0:00:33.932436
Number generated =  19100  time ellapsed =  0:00:34.107488
Number generated =  19200  time ellapsed =  0:00:34.325074
Number generated =  19300  time ellapsed =  0:00:34.479661
Number generated =  19400  time ellapsed =  0:00:34.742922
Number generated =  19500  time ellapsed =  0:00:34.954148
Number generated =  19600  time ellapsed =  0:00:35.201415
Number generated =  19700  time ellapsed =  0:00:35.417324
Number generated =  19800  time ellapsed =  0:00:35.682245
Number generated =  19900  time ellapsed =  0:00:35.833839
Generated